# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

mark a A2
mark b A2
mark c A2
mark d A2
mark e A2
mark f A2
mark g A2
mark h A2
mark i A2
mark j A2
mark k A2
mark l A2
mark m A2
mark n A2
mark o A2
mark p A2
mark q A2
mark r A2
mark s A2
mark t A2
mark u A2
mark v A2
mark w A2
mark x A2
mark y A2
mark z A2
label B4 = "Date"
label C4 = "New Tune"
goto D4
